language: node_js
node_js: "node"
os:
  - linux
  - osx
notifications:
  email: false
install:
  - rm package-lock.json
  - npm install
script:
  - node insertVersion.js
  - rm insertVersion.js
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    npm run distDeb;
    else
    npm run distMac;
    npm run distWin;
    fi
