language: node_js
node_js: "node"
matrix:
  include:
  - os: osx
notifications:
  email: false
install:
  - npm install
script:
  - rm package-lock.json
  - node insertVersion.js
  - rm insertVersion.js
  - npm run dist
