language: node_js
node_js: "node"
matrix:
  include:
    - os: linux
    - os: osx
notifications:
  email: false
install:
  - rm package-lock.json
  - npm install
script:
  - node prebuild.js
  - rm prebuild.js
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    npm run distSnap;
    npm run distDeb;
    else
    npm run distMac;
    npm run distWin;
    fi
