language: node_js
node_js: "node"
matrix:
  include:
    - os: linux
      env: snap=false
    - os: linux
      env: snap=true
    - os: osx
notifications:
  email: false
install:
  - rm package-lock.json
  - npm install
script:
  - node insertVersion.js
  - rm insertVersion.js
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    if [ $snap == "true" ]; then
    npm run distSnap;
    else
    npm run distDeb;
    fi
    else
    npm run distMac;
    npm run distWin;
    fi
