language: node_js
node_js: "node"
matrix:
  include:
  #- os: linux
    #dist: xenial
    #sudo: required
  - os: osx
notifications:
  email: false
script:
  - npm run dist
before_deploy:
    - git config --local user.name "Cory Sanin"
    - git config --local user.email "corysanin@outlook.com"
    - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  file_glob: true
  file:
    - "*.exe"
    - "*.deb"
    - "*.dmg"
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
