language: node_js
node_js: "node"
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: osx
notifications:
  email: false
script:
  - npm run dist
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
